import { TestResult } from "^jatec";

//
// test framework
//

export type MinimalTestId = {
  name: string;
  file: string; //absolute path
  line?: number;
};

export type JarunTestRunner = {
  runTest: (globalId: string, absTestFile: string) => Promise<TestResult>;
  kill: () => Promise<void>;
};

export type TestFrameworkProv<Id extends MinimalTestId> = {
  getTestIds: () => Promise<Id[]>;

  /**
   * - globalId is an opaque string generated by jate.
   *    The test framework should use it to report rogue tests, etc.
   * - testId comes from the individual frameworks. They return it in `getTestIds`.
   */
  runTest: (globalId: string, testId: Id) => Promise<TestResult>;
  kill: () => Promise<void>;
};
