name: "Test"

on: "push"

permissions:
  contents: read

jobs:
  test:
    strategy:
      matrix:
        epoch: [0, 1, 2]
        # epoch: [0, 1, 2, 3]
        # os: [ubuntu-latest, macos-latest, windows-latest]
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      # Hacky, too avoid using `actions/setup-node` another way.
      - name: Get node version
        id: get-node-version
        shell: bash
        run: |
          VERSIONS=(16 18 20);
          INDEX=$((${{ matrix.epoch}} % ${#VERSIONS[@]}))
          echo "node-version=${VERSIONS[$INDEX]}" >> "$GITHUB_OUTPUT"

      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ steps.get-node-version.outputs.node-version }}

      - name: Install epoch ${{ matrix.epoch }}
        shell: bash
        run: |
          chmod +x ./epoch-install.sh
          ./epoch-install.sh ${{ matrix.epoch }}

      - name: Run tests
        run: yarn -s dev-test
